name: CraftCordConnect
version: 1.0.0
main: com.craftcordconnect.CraftCordConnect
api-version: 1.21
authors: [Fate101]
description: Bidirectional communication between Minecraft chat and Discord (CraftCord-Connect)
website: https://github.com/Fate101/CraftCord-Connect

commands:
  craftcord:
    description: Main command for CraftCord-Connect plugin
    usage: /craftcord <reload|toggle|status>
    permission: craftcord.admin
  craftcordtoggle:
    description: Toggle CraftCord-Connect relay for yourself
    usage: /craftcordtoggle [receive|send|all]
    permission: craftcord.toggle

permissions:
  craftcord.admin:
    description: Allows access to admin commands
    default: op
  craftcord.toggle:
    description: Allows users to toggle relay settings
    default: true
  craftcord.send:
    description: Allows sending messages to Discord
    default: true
  craftcord.receive:
    description: Allows receiving messages from Discord
    default: true
  craftcord.player:
    description: Grants all standard player permissions for CraftCord-Connect
    default: true
    children:
      craftcord.toggle: true
      craftcord.send: true
      craftcord.receive: true 